(() => {
 const MAP={job_type:{id:'jobTitle',label:'Job types'},description:{id:'description',label:'Job descriptions'},panel_brand:{id:'panelBrand',label:'Panel brands'},panel_type:{id:'panelType',label:'Panel types / models'},panel_quantity:{id:'panelQuantity',label:'Panel quantities',numeric:true},solar_capacity:{id:'solarCapacity',label:'Solar sizes (kW)',numeric:true},phase_type:{id:'phaseType',label:'Phase types'},battery_brand:{id:'batteryBrand',label:'Battery brands'},battery_type:{id:'batteryType',label:'Battery types / models'},battery_capacity:{id:'batteryCapacity',label:'Battery sizes (kWh)',numeric:true},inverter_brand:{id:'inverterBrand',label:'Inverter brands'},inverter_type:{id:'inverterType',label:'Inverter types / models'},inverter_capacity:{id:'inverterCapacity',label:'Inverter sizes (kW)',numeric:true}};
 const GROUPS={
  job_details:{label:'Job details',sub:'Job type and description',categories:['job_type','description']},
  solar:{label:'System details',sub:'Panel brand, model, quantity, solar size and phase',categories:['panel_brand','panel_type','panel_quantity','solar_capacity','phase_type']},
  battery:{label:'Battery',sub:'Battery brand, model and size',categories:['battery_brand','battery_type','battery_capacity']},
  inverter:{label:'Inverter',sub:'Inverter brand, size and model',categories:['inverter_brand','inverter_capacity','inverter_type']}
 };
 let rows=[],features={},openGroup=null; const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m])); const business=()=>window.SchedulePlusBusiness?.business||null;
 async function loadRows(){const b=business();if(!b)return;const[{data,error},{data:fs,error:fe}]=await Promise.all([supabaseClient.from('business_dropdown_options').select('*').eq('business_id',b.id).order('category').order('sort_order').order('value'),supabaseClient.from('business_feature_settings').select('feature_key,is_enabled').eq('business_id',b.id)]);if(error)throw error;if(fe)throw fe;rows=data||[];features={};(fs||[]).forEach(r=>features[r.feature_key]=r.is_enabled!==false)}
 function groupEnabled(k){return features[k]!==false}
 function vals(c){return rows.filter(r=>r.category===c&&r.is_active).sort((a,b)=>a.sort_order-b.sort_order||a.value.localeCompare(b.value))}
 function populate(c){const el=document.getElementById(MAP[c].id);if(!el||el.tagName!=='SELECT')return;const current=el.value;el.innerHTML='';if(c!=='job_type')el.append(new Option('Not set',''));else el.append(new Option('Select job type',''));vals(c).forEach(r=>el.append(new Option(r.value,r.value)));if(current&&![...el.options].some(o=>o.value===current))el.append(new Option(current,current));if(current)el.value=current}
 function refresh(){Object.keys(MAP).forEach(populate);const tf=document.querySelector('.type-filters');if(tf){const active=document.querySelector('.type-filter.active')?.dataset.type||'all';tf.innerHTML='<button class="type-filter" data-type="all" type="button">All types</button>'+vals('job_type').map(r=>`<button class="type-filter" data-type="${esc(r.value)}" type="button">${esc(r.value)}</button>`).join('');tf.querySelectorAll('.type-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.type-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');try{typeFilter=b.dataset.type;render()}catch(_){}});(tf.querySelector(`[data-type="${CSS.escape(active)}"]`)||tf.querySelector('[data-type="all"]'))?.classList.add('active')}window.dispatchEvent(new Event('scheduleplus:feature-refresh'))}
 function closeDrawer(){document.getElementById('sideMenu')?.classList.remove('open');document.getElementById('drawerBackdrop')?.classList.add('hidden')}
 function clearOpenState(){openGroup=null}
 function ui(){const a=document.querySelector('.menu-profile-actions');if(a&&!document.getElementById('businessConfigBtn')){const b=document.createElement('button');b.id='businessConfigBtn';b.textContent='Configuration';b.onclick=open;a.appendChild(b)}if(document.getElementById('businessConfigDialog'))return;const d=document.createElement('dialog');d.id='businessConfigDialog';d.className='config-dialog';d.innerHTML='<div class="config-card"><div class="dialog-head"><div><p class="eyebrow">BUSINESS SETTINGS</p><h2>Configuration</h2></div><button id="businessConfigClose" class="ghost">✕</button></div><p class="config-intro">Turn job form sections on or off, then expand a section to manage its options.</p><div id="businessConfigBody"></div><p id="businessConfigMessage" class="config-message"></p><div class="dialog-actions"><button id="businessConfigDone" class="primary">Done</button></div></div>';document.getElementById('appView').appendChild(d);d.insertAdjacentHTML('afterend','<dialog id="configEditDialog" class="config-edit-dialog"><div class="config-edit-card"><h3>Edit item</h3><input id="configEditInput"><p id="configEditMessage"></p><div class="config-edit-actions"><button id="configEditCancel">Cancel</button><button id="configEditSave">Save changes</button></div><button id="configEditDelete" class="config-delete">Delete permanently</button></div></dialog>');businessConfigClose.onclick=()=>{clearOpenState();d.close();closeDrawer()};businessConfigDone.onclick=()=>{clearOpenState();d.close();closeDrawer()};d.addEventListener('close',()=>{clearOpenState();closeDrawer()});configEditCancel.onclick=()=>configEditDialog.close()}
 function row(r,on){return `<div class="config-list-row ${on?'':'disabled'}" data-id="${r.id}"><button class="config-item-name" data-edit>${esc(r.value)}</button><button class="config-state-btn ${on?'minus':'plus'}" data-toggle>${on?'−':'+'}</button></div>`}
 function categoryHtml(c){const m=MAP[c],all=rows.filter(r=>r.category===c),on=all.filter(r=>r.is_active),off=all.filter(r=>!r.is_active);return `<details class="config-subcategory" data-category="${c}"><summary><span>${m.label}</span><span class="config-count">${on.length}</span></summary><div class="config-subcategory-body"><div class="config-add-row"><input data-new placeholder="Add new"><button data-add>+ Add</button></div><div class="config-simple-list">${on.map(r=>row(r,true)).join('')||'<div class="config-empty">No active items.</div>'}</div>${off.length?`<div class="config-disabled-label">Disabled</div><div class="config-simple-list disabled-list">${off.map(r=>row(r,false)).join('')}</div>`:''}</div></details>`}
 function renderConfig(){ui();businessConfigBody.innerHTML=Object.entries(GROUPS).map(([g,info])=>{const on=groupEnabled(g);return `<details class="config-category ${on?'':'group-off'}" data-group="${g}" ${openGroup===g?'open':''}><summary><span class="config-group-summary"><span class="config-group-copy"><strong>${info.label}</strong><small>${info.sub}</small></span><label class="config-group-switch" title="Turn ${info.label} on or off"><input data-group-toggle type="checkbox" ${on?'checked':''}><span class="config-switch-ui"></span></label></span></summary><div class="config-category-body">${info.categories.map(categoryHtml).join('')}</div></details>`}).join('');businessConfigBody.querySelectorAll('.config-category').forEach(d=>d.ontoggle=()=>{if(d.open){openGroup=d.dataset.group;businessConfigBody.querySelectorAll('.config-category').forEach(x=>{if(x!==d)x.open=false})}else if(openGroup===d.dataset.group){openGroup=null}});businessConfigBody.querySelectorAll('[data-group-toggle]').forEach(i=>i.onclick=e=>e.stopPropagation());businessConfigBody.querySelectorAll('[data-group-toggle]').forEach(i=>i.onchange=()=>toggleGroup(i.closest('.config-category').dataset.group,i.checked));businessConfigBody.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.closest('.config-subcategory')));businessConfigBody.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(b.closest('.config-list-row')));businessConfigBody.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.closest('.config-list-row')))}
 function msg(t){businessConfigMessage.textContent=t||''}
 async function toggleGroup(group,isEnabled){const b=business();const{error}=await supabaseClient.from('business_feature_settings').upsert({business_id:b.id,feature_key:group,is_enabled:isEnabled,updated_at:new Date().toISOString()},{onConflict:'business_id,feature_key'});if(error){msg(error.message);return}features[group]=isEnabled;renderConfig();refresh();msg(`${GROUPS[group].label} ${isEnabled?'enabled':'disabled'}. Existing job data is kept.`)}
 async function add(s){const c=s.dataset.category,i=s.querySelector('[data-new]'),v=i.value.trim();if(!v)return msg('Enter a value.');const{error}=await supabaseClient.from('business_dropdown_options').insert({business_id:business().id,category:c,value:v,sort_order:1000});if(error)return msg(error.code==='23505'?'That option already exists.':error.message);await loadRows();renderConfig();refresh();msg('Option added.')}
 async function toggle(el){const r=rows.find(x=>x.id===el.dataset.id);if(!r)return;await supabaseClient.from('business_dropdown_options').update({is_active:!r.is_active,updated_at:new Date().toISOString()}).eq('id',r.id).eq('business_id',business().id);await loadRows();renderConfig();refresh()}
 function edit(el){const r=rows.find(x=>x.id===el.dataset.id);if(!r)return;configEditInput.value=r.value;configEditMessage.textContent='';configEditSave.onclick=()=>save(r);configEditDelete.onclick=()=>del(r);configEditDialog.showModal()}
 async function save(r){const v=configEditInput.value.trim();if(!v)return configEditMessage.textContent='Enter a value.';const{error}=await supabaseClient.from('business_dropdown_options').update({value:v,updated_at:new Date().toISOString()}).eq('id',r.id).eq('business_id',business().id);if(error)return configEditMessage.textContent=error.message;configEditDialog.close();await loadRows();renderConfig();refresh()}
 async function del(r){if(!confirm(`Delete “${r.value}” permanently?\n\nExisting jobs will keep their saved value.`))return;const{error}=await supabaseClient.from('business_dropdown_options').delete().eq('id',r.id).eq('business_id',business().id);if(error)return configEditMessage.textContent=error.message;configEditDialog.close();await loadRows();renderConfig();refresh()}
 async function open(){clearOpenState();closeDrawer();await loadRows();renderConfig();businessConfigDialog.showModal()}
 async function init(){let n=0;while(!business()&&n++<80)await new Promise(r=>setTimeout(r,100));if(!business())return;ui();await loadRows();refresh()}
 if(document.readyState==='complete')init();else addEventListener('load',init,{once:true});
})();