(() => {
 const MAP={job_type:{id:'jobTitle',label:'Job types'},status:{id:'status',label:'Statuses'},priority:{id:'priority',label:'Priorities'},description:{id:'description',label:'Job descriptions'},panel_brand:{id:'panelBrand',label:'Panel brands'},panel_type:{id:'panelType',label:'Panel types / models'},panel_quantity:{id:'panelQuantity',label:'Panel quantities',numeric:true},solar_capacity:{id:'solarCapacity',label:'Solar sizes (kW)',numeric:true},phase_type:{id:'phaseType',label:'Phase types'},battery_brand:{id:'batteryBrand',label:'Battery brands'},battery_type:{id:'batteryType',label:'Battery types / models'},battery_capacity:{id:'batteryCapacity',label:'Battery sizes (kWh)',numeric:true},inverter_brand:{id:'inverterBrand',label:'Inverter brands'},inverter_type:{id:'inverterType',label:'Inverter types / models'},inverter_capacity:{id:'inverterCapacity',label:'Inverter sizes (kW)',numeric:true}};
 const DEFAULTS={job_type:['Battery','Solar','Battery + Solar'],status:['New','To schedule','Scheduled','In progress','Follow-Up','Completed'],priority:['Normal','High','Urgent'],description:['Installation','Replacement','Upgrade','Service / repair','Fault finding','Site inspection'],panel_brand:['Aiko','Canadian Solar','Jinko','LONGi','REC','Trina'],panel_type:[],panel_quantity:['6','8','10','12','14','16','18','20','22','24','30','40'],solar_capacity:['3.3','5','6.6','8','10','13.2','15','20'],phase_type:['Single phase','Three phase'],battery_brand:['BYD','Enphase','Sigenergy','Sungrow','Tesla'],battery_type:[],battery_capacity:['5','10','13.5','20','25','30'],inverter_brand:['Enphase','Fronius','GoodWe','Huawei','Sigenergy','SMA','SolarEdge','Sungrow'],inverter_type:[],inverter_capacity:['5','6','8','10','15','20']};
 const STATUS_KEYS={'New':'new','To schedule':'to_schedule','Scheduled':'scheduled','In progress':'in_progress','Follow-Up':'waiting','Completed':'completed'}; const PRIORITY_KEYS={'Normal':'normal','Low':'low','High':'high','Urgent':'urgent'};
 let rows=[],openCategory='job_type'; const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); const business=()=>window.SchedulePlusBusiness?.business||null,membership=()=>window.SchedulePlusBusiness?.membership||null,canManage=()=>['owner','admin'].includes(membership()?.role);
 async function loadRows(){const{data,error}=await supabaseClient.from('business_dropdown_options').select('*').eq('business_id',business().id).order('category').order('sort_order').order('value');if(error)throw error;rows=data||[]}
 function vals(c){return rows.filter(r=>r.category===c&&r.is_active).sort((a,b)=>a.sort_order-b.sort_order||a.value.localeCompare(b.value))}
 function key(c,v){return c==='status'?(STATUS_KEYS[v]||v):c==='priority'?(PRIORITY_KEYS[v]||v.toLowerCase().replace(/\s+/g,'_')):v}
 function populate(c){const el=document.getElementById(MAP[c].id);if(!el||el.tagName!=='SELECT')return;const current=el.value;el.innerHTML='';if(!['status','priority'].includes(c))el.append(new Option(c==='job_type'?'Select job type':'Not set',''));vals(c).forEach(r=>el.append(new Option(r.value,key(c,r.value))));if(current&&![...el.options].some(o=>o.value===current))el.append(new Option(current,current));if(current)el.value=current}
 function refresh(){Object.keys(MAP).forEach(populate);const sf=document.getElementById('statusFilter');if(sf){const cur=sf.value;sf.innerHTML='<option value="">All statuses</option>';vals('status').forEach(r=>sf.append(new Option(r.value,key('status',r.value))));sf.value=cur}const tf=document.querySelector('.type-filters');if(tf){const active=document.querySelector('.type-filter.active')?.dataset.type||'all';tf.innerHTML='<button class="type-filter" data-type="all" type="button">All types</button>'+vals('job_type').map(r=>`<button class="type-filter" data-type="${esc(r.value)}" type="button">${esc(r.value)}</button>`).join('');tf.querySelectorAll('.type-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.type-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');try{typeFilter=b.dataset.type;render()}catch(_){}});(tf.querySelector(`[data-type="${CSS.escape(active)}"]`)||tf.querySelector('[data-type="all"]'))?.classList.add('active')}}
 function ui(){const a=document.querySelector('.menu-profile-actions');if(a&&!document.getElementById('businessConfigBtn')){const b=document.createElement('button');b.id='businessConfigBtn';b.textContent='Configuration';b.onclick=open;a.appendChild(b)}if(document.getElementById('businessConfigDialog'))return;const d=document.createElement('dialog');d.id='businessConfigDialog';d.className='config-dialog';d.innerHTML='<div class="config-card"><div class="dialog-head"><div><p class="eyebrow">BUSINESS SETTINGS</p><h2>Configuration</h2></div><button id="businessConfigClose" class="ghost">✕</button></div><p class="config-intro">Choose how this business organises its jobs.</p><div id="businessConfigBody"></div><p id="businessConfigMessage" class="config-message"></p><div class="dialog-actions"><button id="businessConfigDone" class="primary">Done</button></div></div>';document.getElementById('appView').appendChild(d);d.insertAdjacentHTML('afterend','<dialog id="configEditDialog" class="config-edit-dialog"><div class="config-edit-card"><h3>Edit item</h3><input id="configEditInput"><p id="configEditMessage"></p><div class="config-edit-actions"><button id="configEditCancel">Cancel</button><button id="configEditSave">Save changes</button></div><button id="configEditDelete" class="config-delete">Delete permanently</button></div></dialog>');businessConfigClose.onclick=()=>d.close();businessConfigDone.onclick=()=>d.close();configEditCancel.onclick=()=>configEditDialog.close()}
 function row(r,on){return `<div class="config-list-row ${on?'':'disabled'}" data-id="${r.id}"><button class="config-item-name" data-edit>${esc(r.value)}</button><button class="config-state-btn ${on?'minus':'plus'}" data-toggle>${on?'−':'+'}</button></div>`}
 function renderConfig(){ui();businessConfigBody.innerHTML=Object.entries(MAP).map(([c,m])=>{const all=rows.filter(r=>r.category===c),on=all.filter(r=>r.is_active),off=all.filter(r=>!r.is_active);return `<details class="config-category" data-category="${c}" ${openCategory===c?'open':''}><summary><span>${m.label}</span><span class="config-count">${on.length}</span></summary><div class="config-category-body"><div class="config-add-row"><input data-new placeholder="Add new"><button data-add>+ Add</button></div><div class="config-simple-list">${on.map(r=>row(r,true)).join('')||'<div class="config-empty">No active items.</div>'}</div>${off.length?`<div class="config-disabled-label">Disabled</div><div class="config-simple-list disabled-list">${off.map(r=>row(r,false)).join('')}</div>`:''}</div></details>`}).join('');businessConfigBody.querySelectorAll('details').forEach(d=>d.ontoggle=()=>{if(d.open){openCategory=d.dataset.category;businessConfigBody.querySelectorAll('details').forEach(x=>{if(x!==d)x.open=false})}});businessConfigBody.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.closest('details')));businessConfigBody.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(b.closest('.config-list-row')));businessConfigBody.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.closest('.config-list-row')))}
 function msg(t){businessConfigMessage.textContent=t||''} async function add(s){const c=s.dataset.category,i=s.querySelector('[data-new]'),v=i.value.trim();if(!v)return msg('Enter a value.');const{error}=await supabaseClient.from('business_dropdown_options').insert({business_id:business().id,category:c,value:v,sort_order:1000});if(error)return msg(error.code==='23505'?'That option already exists.':error.message);await loadRows();renderConfig();refresh();msg('Option added.')}
 async function toggle(el){const r=rows.find(x=>x.id===el.dataset.id);if(!r)return;await supabaseClient.from('business_dropdown_options').update({is_active:!r.is_active,updated_at:new Date().toISOString()}).eq('id',r.id).eq('business_id',business().id);await loadRows();renderConfig();refresh()}
 function edit(el){const r=rows.find(x=>x.id===el.dataset.id);if(!r)return;configEditInput.value=r.value;configEditMessage.textContent='';configEditSave.onclick=()=>save(r);configEditDelete.onclick=()=>del(r);configEditDialog.showModal()}
 async function save(r){const v=configEditInput.value.trim();if(!v)return configEditMessage.textContent='Enter a value.';const{error}=await supabaseClient.from('business_dropdown_options').update({value:v,updated_at:new Date().toISOString()}).eq('id',r.id).eq('business_id',business().id);if(error)return configEditMessage.textContent=error.message;configEditDialog.close();await loadRows();renderConfig();refresh()}
 async function del(r){if(!confirm(`Delete “${r.value}” permanently?\n\nExisting jobs will keep their saved value.`))return;const{error}=await supabaseClient.from('business_dropdown_options').delete().eq('id',r.id).eq('business_id',business().id);if(error)return configEditMessage.textContent=error.message;configEditDialog.close();await loadRows();renderConfig();refresh()}
 async function open(){document.getElementById('sideMenu')?.classList.remove('open');businessConfigDialog.showModal();await loadRows();renderConfig()}
 async function init(){let n=0;while(!business()&&n++<80)await new Promise(r=>setTimeout(r,100));if(!business())return;ui();await loadRows();refresh()}
 if(document.readyState==='complete')init();else addEventListener('load',init,{once:true});
})();