(() => {
  const ACTIVE_BUSINESS_KEY='schedule_plus_active_business', BRAND_CACHE_KEY='schedule_plus_brand_cache', DEFAULT_LOGO='assets/icons/icon.svg';
  const VANILLA_MODE=new URLSearchParams(location.search).get('new')==='1';
  const state={business:null,membership:null,memberships:[]};
  const validHex=(v,f)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?v:f;
  function cacheBrand(b){try{localStorage.setItem(BRAND_CACHE_KEY,JSON.stringify({business_name:b?.business_name,logo_url:b?.logo_url,accent_color:b?.accent_color,secondary_color:b?.secondary_color}))}catch(_){}}
  function cachedBrand(){try{return JSON.parse(localStorage.getItem(BRAND_CACHE_KEY)||'null')}catch(_){return null}}
  function canManage(){return ['owner','admin'].includes(state.membership?.role)}
  function closeMenu(){document.getElementById('sideMenu')?.classList.remove('open');document.getElementById('drawerBackdrop')?.classList.add('hidden')}
  function applyVanillaBranding(){
    document.documentElement.style.setProperty('--tenant-accent','#6b7280');
    document.documentElement.style.setProperty('--tenant-secondary','#9ca3af');
    document.querySelectorAll('.auth-logo').forEach(i=>{i.src=DEFAULT_LOGO;i.alt='Schedule+ logo'});
    document.title='Schedule+';
  }
  function ensureUi(){
    if(document.getElementById('businessSettingsBtn'))return;
    const actions=document.querySelector('.menu-profile-actions');
    if(actions){
      const settings=document.createElement('button');settings.id='businessSettingsBtn';settings.className='tenant-settings-btn';settings.type='button';settings.textContent='Business settings';actions.appendChild(settings);
      const users=document.createElement('button');users.id='businessUsersBtn';users.className='tenant-settings-btn';users.type='button';users.textContent='Users & staff';actions.appendChild(users);
    }
    const app=document.getElementById('appView')||document.body;
    const settings=document.createElement('dialog');settings.id='businessSettingsDialog';settings.className='tenant-dialog';settings.innerHTML=`<div class="tenant-card"><div class="dialog-head"><div><h2>Business settings</h2><span id="businessRole" class="tenant-role"></span></div><button id="businessSettingsClose" class="ghost" type="button">✕</button></div><form id="businessSettingsForm" class="tenant-form"><div class="tenant-logo-row"><img id="businessLogoPreview" class="tenant-logo-preview" src="${DEFAULT_LOGO}" alt="Business logo preview"><div><label>Business logo<input id="businessLogoFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label><div class="tenant-logo-help">PNG, JPG, WebP or SVG, up to 2 MB.</div></div></div><label>Business name<input id="businessNameInput" maxlength="100" required></label><div class="tenant-grid2"><label>Phone<input id="businessPhoneInput" type="tel"></label><label>Email<input id="businessEmailInput" type="email"></label></div><label>Business address<textarea id="businessAddressInput" rows="2"></textarea></label><div class="tenant-grid2"><label>Primary colour<div class="tenant-colour"><input id="businessAccentInput" type="color" value="#ff00a8"><input id="businessAccentText" maxlength="7" value="#ff00a8"></div></label><label>Secondary colour<div class="tenant-colour"><input id="businessSecondaryInput" type="color" value="#0d9488"><input id="businessSecondaryText" maxlength="7" value="#0d9488"></div></label></div><div id="businessReadonly" class="tenant-readonly hidden">Only a business owner or admin can change these settings.</div><p id="businessSettingsMessage" class="tenant-message"></p><div class="dialog-actions"><button id="businessSettingsCancel" class="secondary" type="button">Cancel</button><button id="businessSettingsSave" class="primary" type="submit">Save business</button></div></form></div>`;app.appendChild(settings);
    const users=document.createElement('dialog');users.id='businessUsersDialog';users.className='tenant-dialog';users.innerHTML=`<div class="tenant-card"><div class="dialog-head"><div><h2>Users & staff</h2><span id="usersBusinessName" class="muted"></span></div><button id="businessUsersClose" class="ghost" type="button">✕</button></div><div id="businessUsersList" class="tenant-users-list"></div><form id="addBusinessUserForm" class="tenant-form tenant-add-user"><h3>Invite staff member</h3><p class="tenant-logo-help">Enter their email and Schedule+ will invite them into this business.</p><label>Email<input id="newBusinessUserEmail" type="email" required placeholder="staff@example.com"></label><label>Access level<select id="newBusinessUserRole"><option value="member">Member</option><option value="admin">Admin</option></select></label><button class="primary" type="submit">Send invitation</button></form><p id="businessUsersMessage" class="tenant-message"></p></div>`;app.appendChild(users);
    const onboarding=document.createElement('dialog');onboarding.id='businessOnboardingDialog';onboarding.className='tenant-dialog tenant-onboarding';onboarding.innerHTML=`<div class="tenant-card"><div><p class="eyebrow">SCHEDULE+ SETUP</p><h2>Create your business</h2></div><p class="tenant-onboarding-copy">Create your private Schedule+ workspace. Your jobs, users and branding will be kept separate from every other business.</p><form id="businessOnboardingForm" class="tenant-form"><label>Business name<input id="onboardingBusinessName" maxlength="100" placeholder="e.g. Smith Electrical" required></label><p id="businessOnboardingMessage" class="tenant-message"></p><button class="primary" type="submit">Create business</button></form></div>`;app.appendChild(onboarding);
    const password=document.createElement('dialog');password.id='invitePasswordDialog';password.className='tenant-dialog tenant-onboarding';password.innerHTML=`<div class="tenant-card"><div><p class="eyebrow">WELCOME TO SCHEDULE+</p><h2>Set your password</h2></div><p class="tenant-onboarding-copy">Your invitation has been accepted. Create a password so you can sign in normally next time.</p><form id="invitePasswordForm" class="tenant-form"><label>New password<input id="invitePassword" type="password" minlength="6" autocomplete="new-password" required></label><label>Confirm password<input id="invitePasswordConfirm" type="password" minlength="6" autocomplete="new-password" required></label><p id="invitePasswordMessage" class="tenant-message"></p><button class="primary" type="submit">Save password</button></form></div>`;app.appendChild(password);
    businessSettingsBtn.onclick=openSettings;businessUsersBtn.onclick=openUsers;businessSettingsClose.onclick=()=>settings.close();businessSettingsCancel.onclick=()=>settings.close();businessUsersClose.onclick=()=>users.close();businessSettingsForm.onsubmit=saveSettings;businessOnboardingForm.onsubmit=createBusiness;businessLogoFile.onchange=previewLogo;addBusinessUserForm.onsubmit=addUser;invitePasswordForm.onsubmit=saveInvitePassword;
    bindColourPair('businessAccentInput','businessAccentText','#ff00a8');bindColourPair('businessSecondaryInput','businessSecondaryText','#0d9488');
  }
  function bindColourPair(a,t,f){const p=document.getElementById(a),x=document.getElementById(t);if(!p||!x)return;p.oninput=()=>x.value=p.value;x.oninput=()=>{const v=validHex(x.value,null);if(v)p.value=v};x.onblur=()=>{const v=validHex(x.value,f);x.value=v;p.value=v}}
  function previewLogo(e){const f=e.target.files?.[0];if(!f)return;if(f.size>2097152){alert('Logo must be 2 MB or smaller.');e.target.value='';return}businessLogoPreview.src=URL.createObjectURL(f)}
  function applyBranding(b){if(!b)return;document.documentElement.style.setProperty('--tenant-accent',validHex(b.accent_color,'#ff00a8'));document.documentElement.style.setProperty('--tenant-secondary',validHex(b.secondary_color,'#0d9488'));const logo=b.logo_url||DEFAULT_LOGO;document.querySelectorAll('.topbar .brand img,.side-menu-head img,.auth-logo').forEach(i=>{i.src=logo;i.alt=`${b.business_name||'Business'} logo`});const h=document.querySelector('.side-menu-head > div');if(h){let el=document.getElementById('tenantBusinessName');if(!el){el=document.createElement('span');el.id='tenantBusinessName';el.className='tenant-business-name';h.appendChild(el)}el.textContent=b.business_name||'Business'}const eyebrow=document.querySelector('#dashboardView .hero-row .eyebrow');if(eyebrow)eyebrow.textContent=b.business_name?`JOB ORGANISER · ${b.business_name.toUpperCase()}`:'JOB ORGANISER';document.title=`${b.app_name||'Schedule+'} · ${b.business_name||'Business'}`;cacheBrand(b)}
  function applyCachedBrand(){if(VANILLA_MODE){applyVanillaBranding();return}const b=cachedBrand();if(b)applyBranding({...b,app_name:'Schedule+'});else applyVanillaBranding()}
  async function invoke(name,body){const {data,error}=await supabaseClient.functions.invoke(name,{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
  async function claimPendingInvites(){try{return await invoke('claim-business-invite',{})}catch(err){console.warn('Could not claim Schedule+ invitation',err);return null}}
  async function loadContext(){
    const {data:{session}}=await supabaseClient.auth.getSession();const user=session?.user;if(!user){if(VANILLA_MODE)applyVanillaBranding();return false}
    await claimPendingInvites();
    const {data,error}=await supabaseClient.from('business_users').select('business_id,role,is_active').eq('user_id',user.id).eq('is_active',true);if(error)return false;
    state.memberships=data||[];
    if(!state.memberships.length){state.business=null;state.membership=null;applyVanillaBranding();showOnboarding();return false}
    let id=localStorage.getItem(ACTIVE_BUSINESS_KEY);if(!state.memberships.some(m=>m.business_id===id))id=state.memberships[0].business_id;localStorage.setItem(ACTIVE_BUSINESS_KEY,id);state.membership=state.memberships.find(m=>m.business_id===id)||state.memberships[0];
    const {data:b,error:e}=await supabaseClient.from('businesses').select('*').eq('id',state.membership.business_id).single();if(e)return false;state.business=b;applyBranding(b);
    if(VANILLA_MODE)history.replaceState({},'',location.pathname);
    const fresh=(await supabaseClient.auth.getUser()).data?.user;if(fresh?.user_metadata?.schedule_plus_invited&&!fresh?.user_metadata?.schedule_plus_password_set)showInvitePassword();
    return true
  }
  window.SchedulePlusBusiness={get business(){return state.business},get membership(){return state.membership},get memberships(){return state.memberships},reload:loadContext};
  function showOnboarding(){ensureUi();const d=document.getElementById('businessOnboardingDialog');if(d&&!d.open)d.showModal()}
  function showInvitePassword(){ensureUi();const d=document.getElementById('invitePasswordDialog');if(d&&!d.open)d.showModal()}
  async function saveInvitePassword(e){e.preventDefault();const p=invitePassword.value,c=invitePasswordConfirm.value;if(p.length<6){invitePasswordMessage.textContent='Password must be at least 6 characters.';return}if(p!==c){invitePasswordMessage.textContent='Passwords do not match.';return}const btn=e.submitter;btn.disabled=true;btn.textContent='Saving…';const {error}=await supabaseClient.auth.updateUser({password:p,data:{schedule_plus_invited:true,schedule_plus_password_set:true}});btn.disabled=false;btn.textContent='Save password';if(error){invitePasswordMessage.textContent=error.message;return}invitePasswordDialog.close()}
  async function createBusiness(e){e.preventDefault();const name=onboardingBusinessName.value.trim();if(name.length<2){businessOnboardingMessage.textContent='Enter a business name.';return}const btn=e.submitter;btn.disabled=true;btn.textContent='Creating…';const {error}=await supabaseClient.rpc('create_business_for_current_user',{p_business_name:name,p_slug:null});btn.disabled=false;btn.textContent='Create business';if(error){businessOnboardingMessage.textContent=error.message;return}businessOnboardingDialog.close();history.replaceState({},'',location.pathname);await loadContext();if(typeof loadJobs==='function')await loadJobs()}
  function openSettings(){ensureUi();const b=state.business;if(!b)return showOnboarding();const edit=canManage();businessRole.textContent=state.membership?.role||'member';businessNameInput.value=b.business_name||'';businessPhoneInput.value=b.phone||'';businessEmailInput.value=b.email||'';businessAddressInput.value=b.address||'';const a=validHex(b.accent_color,'#ff00a8'),s=validHex(b.secondary_color,'#0d9488');businessAccentInput.value=businessAccentText.value=a;businessSecondaryInput.value=businessSecondaryText.value=s;businessLogoPreview.src=b.logo_url||DEFAULT_LOGO;businessLogoFile.value='';businessSettingsMessage.textContent='';businessReadonly.classList.toggle('hidden',edit);document.querySelectorAll('#businessSettingsForm input,#businessSettingsForm textarea').forEach(el=>el.disabled=!edit);businessSettingsCancel.disabled=false;businessSettingsSave.classList.toggle('hidden',!edit);businessSettingsDialog.showModal();closeMenu()}
  async function uploadLogo(file){if(!file)return state.business?.logo_url||null;if(file.size>2097152)throw new Error('Logo must be 2 MB or smaller.');const ext=(file.name.split('.').pop()||'png').toLowerCase().replace(/[^a-z0-9]/g,'')||'png',path=`${state.business.id}/logo-${Date.now()}.${ext}`;const {error}=await supabaseClient.storage.from('business-logos').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(error)throw error;return supabaseClient.storage.from('business-logos').getPublicUrl(path).data.publicUrl}
  async function saveSettings(e){e.preventDefault();if(!state.business||!canManage())return;const save=businessSettingsSave,name=businessNameInput.value.trim();if(name.length<2){businessSettingsMessage.textContent='Business name must be at least 2 characters.';return}save.disabled=true;save.textContent='Saving…';try{const logo_url=await uploadLogo(businessLogoFile.files?.[0]);const payload={business_name:name,phone:businessPhoneInput.value.trim()||null,email:businessEmailInput.value.trim()||null,address:businessAddressInput.value.trim()||null,accent_color:validHex(businessAccentText.value,'#ff00a8'),secondary_color:validHex(businessSecondaryText.value,'#0d9488'),logo_url};const {data,error}=await supabaseClient.from('businesses').update(payload).eq('id',state.business.id).select('*').single();if(error)throw error;state.business=data;applyBranding(data);businessSettingsMessage.textContent='Business settings saved.';businessSettingsMessage.classList.add('ok');setTimeout(()=>businessSettingsDialog.close(),450)}catch(err){businessSettingsMessage.textContent=err?.message||'Could not save business settings.'}finally{save.disabled=false;save.textContent='Save business'}}
  async function openUsers(){ensureUi();if(!state.business)return;usersBusinessName.textContent=state.business.business_name||'';businessUsersMessage.textContent='';addBusinessUserForm.classList.toggle('hidden',!canManage());businessUsersDialog.showModal();closeMenu();await renderUsers()}
  async function renderUsers(){businessUsersList.innerHTML='<div class="tenant-readonly">Loading users…</div>';try{const data=await invoke('list-business-users',{business_id:state.business.id});businessUsersList.innerHTML=(data.users||[]).map(u=>`<div class="tenant-user-row"><div class="tenant-user-main"><strong>${escapeHtml(u.display_name||u.email||'User')}</strong><small>${escapeHtml(u.email||'')}</small></div><div class="tenant-user-actions">${u.role==='owner'?'<span class="tenant-role">Owner</span>':canManage()?`<select class="tenant-role-select" data-user="${u.user_id}"><option value="member" ${u.role==='member'?'selected':''}>Member</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select><button class="tenant-remove-user" data-user="${u.user_id}" type="button">Remove</button>`:`<span class="tenant-role">${escapeHtml(u.role)}</span>`}</div></div>`).join('')||'<div class="tenant-readonly">No users found.</div>';document.querySelectorAll('.tenant-role-select').forEach(s=>s.onchange=()=>changeRole(s.dataset.user,s.value));document.querySelectorAll('.tenant-remove-user').forEach(b=>b.onclick=()=>removeUser(b.dataset.user))}catch(e){businessUsersList.innerHTML=`<div class="tenant-readonly">${escapeHtml(e.message||'Could not load users.')}</div>`}}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  async function addUser(e){e.preventDefault();const email=newBusinessUserEmail.value.trim(),role=newBusinessUserRole.value;const btn=e.submitter;btn.disabled=true;btn.textContent='Sending…';businessUsersMessage.textContent='';try{const result=await invoke('manage-business-user',{action:'add',business_id:state.business.id,email,role});newBusinessUserEmail.value='';businessUsersMessage.textContent=result.mode==='invited'?'Invitation email sent. They will join this business automatically when they accept it.':'Existing Schedule+ account added to this business.';businessUsersMessage.classList.add('ok');await renderUsers()}catch(err){businessUsersMessage.textContent=err.message||'Could not invite user.'}finally{btn.disabled=false;btn.textContent='Send invitation'}}
  async function changeRole(user_id,role){businessUsersMessage.textContent='Saving role…';try{await invoke('manage-business-user',{action:'role',business_id:state.business.id,user_id,role});businessUsersMessage.textContent='Role updated.';businessUsersMessage.classList.add('ok');await renderUsers()}catch(err){businessUsersMessage.textContent=err.message;await renderUsers()}}
  async function removeUser(user_id){if(!confirm('Remove this user from the business?'))return;businessUsersMessage.textContent='Removing…';try{await invoke('manage-business-user',{action:'remove',business_id:state.business.id,user_id});businessUsersMessage.textContent='User removed.';businessUsersMessage.classList.add('ok');await renderUsers()}catch(err){businessUsersMessage.textContent=err.message}}
  async function boot(){ensureUi();applyCachedBrand();await loadContext()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){state.business=null;state.membership=null;state.memberships=[];if(VANILLA_MODE)applyVanillaBranding();return}if(session?.user)setTimeout(loadContext,0)});
})();