(()=>{
 const PHONE='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.7 3.5 9.2 8l-1.8 1.7c1.3 2.8 3.1 4.6 5.9 5.9l1.7-1.8 4.5 2.5-.7 3.1c-.2.8-.9 1.4-1.8 1.4C9.3 20.8 3.2 14.7 3.2 7c0-.9.6-1.6 1.4-1.8z"/></svg>';
 const CAL='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2v4M18 2v4M3 9h18M5 4h14a2 2 0 0 1 2 2v15H3V6a2 2 0 0 1 2-2z"/></svg>';
 let selected='all';
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const data=()=>{try{if(Array.isArray(window.jobs))return window.jobs;if(typeof jobs!=='undefined'&&Array.isArray(jobs))return jobs}catch(_){}return[]};
 const norm=v=>String(v||'').trim().toLowerCase().replace(/[\s_-]+/g,'');
 const label=j=>({new:'New',to_schedule:'To schedule',scheduled:'Scheduled',in_progress:'In Progress',waiting:'Follow-Up',completed:'Completed'}[j?.status]||String(j?.status||'').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())||'Unscheduled');
 const follow=j=>norm(j?.status)==='waiting'||norm(label(j)).includes('followup');
 const complete=j=>norm(j?.status)==='completed'||norm(label(j)).includes('completed');
 const match=(j,k)=>k==='all'||(k==='scheduled'&&!!j.scheduled_date&&!complete(j)&&!follow(j))||(k==='progress'&&norm(label(j)).includes('inprogress'))||(k==='followup'&&follow(j))||(k==='completed'&&complete(j))||(k==='overdue'&&!!j.scheduled_date&&j.scheduled_date<(typeof localDate==='function'?localDate():new Date().toISOString().slice(0,10))&&!complete(j));
 const tone=j=>{const x=norm(label(j));return x.includes('site')?'site':x.includes('progress')?'progress':x.includes('follow')?'followup':x.includes('complete')?'completed':x.includes('schedule')?'scheduled':'new'};
 const suburb=j=>j?.suburb||(typeof suburbFromAddress==='function'?suburbFromAddress(j?.address_line||''):'')||'Suburb not set';
 const date=(v,t='')=>{if(!v)return'Unscheduled';const d=new Date(`${v}T12:00:00`);return `${new Intl.DateTimeFormat('en-AU',{weekday:'short'}).format(d)} ${String(d.getDate()).padStart(2,'0')} ${new Intl.DateTimeFormat('en-AU',{month:'short'}).format(d)}${t?` [${t}]`:''}`};
 const key=(tile,i)=>{const s=(tile.querySelector('span')?.textContent||'').toLowerCase();return s.includes('total')?'all':s.includes('schedul')?'scheduled':s.includes('progress')?'progress':s.includes('follow')?'followup':s.includes('complete')?'completed':s.includes('overdue')?'overdue':['all','scheduled','progress','followup','completed','overdue'][i]};
 function card(j){const p=j.customer_phone?`<a data-phone class="sp-phone icon-only" href="tel:${esc(String(j.customer_phone).replace(/\s+/g,''))}" aria-label="Call ${esc(j.customer_name||'customer')}">${PHONE}</a>`:`<span class="sp-phone icon-only missing">${PHONE}</span>`;return `<article class="sp-home-job" data-id="${esc(j.id)}"><div class="sp-home-job-top"><strong>${esc(j.customer_name||'No customer')}</strong><span class="sp-status" data-tone="${tone(j)}">${esc(label(j))}</span></div><div class="sp-home-job-suburb">${esc(suburb(j))}</div><div class="sp-home-job-bottom"><span>${esc(j.title||'Job')}</span><span class="sp-date">${CAL}<span>${esc(date(j.scheduled_date,j.time_of_day||''))}</span></span>${p}</div></article>`}
 function arrange(){const home=document.getElementById('spHomeView'),left=home?.querySelector('.sp-home-left'),title=home?.querySelector('.sp-section-title'),root=document.getElementById('spUpcoming');if(!home||!left||!title||!root)return false;let scroll=home.querySelector('.sp-home-scroll');if(!scroll){scroll=root.parentElement;scroll.classList.add('sp-home-scroll')}if(title.parentElement!==left)left.appendChild(title);return true}
 function render(){if(!arrange())return;const stats=document.getElementById('spStats'),root=document.getElementById('spUpcoming');if(!stats||!root)return;const all=data();[...stats.querySelectorAll('.sp-stat-tile')].forEach((t,i)=>{const k=key(t,i);t.dataset.homeFilter=k;t.classList.toggle('selected',k===selected);const n=t.querySelector('strong');if(n)n.textContent=String(all.filter(j=>match(j,k)).length)});const rows=all.filter(j=>match(j,selected)).sort((a,b)=>(a.scheduled_date||'9999').localeCompare(b.scheduled_date||'9999')||(a.scheduled_start||'99:99').localeCompare(b.scheduled_start||'99:99'));root.innerHTML=rows.length?rows.map(card).join(''):'<div class="sp-home-empty">No jobs in this category.</div>';root.querySelectorAll('.sp-home-job').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-phone]'))return;const j=all.find(x=>String(x.id)===String(el.dataset.id));if(j&&typeof openJob==='function')openJob(j)});root.querySelectorAll('[data-phone]').forEach(a=>a.onclick=e=>e.stopPropagation())}
 function bind(){const stats=document.getElementById('spStats');if(!stats||stats.dataset.homeDelegated)return false;stats.dataset.homeDelegated='1';stats.addEventListener('click',e=>{const t=e.target.closest('.sp-stat-tile');if(!t)return;e.preventDefault();e.stopImmediatePropagation();selected=t.dataset.homeFilter||key(t,[...stats.children].indexOf(t));render()},true);return true}
 function syncLogo(){if(window.SchedulePlusAppearance?.updateBrandLogo)window.SchedulePlusAppearance.updateBrandLogo();const b=window.SchedulePlusBusiness?.business,img=document.getElementById('spHomeLogo');if(b&&img){const light=document.documentElement.dataset.theme==='light';img.src=light?(b.logo_light_url||b.logo_dark_url||b.logo_url||img.src):(b.logo_dark_url||b.logo_url||b.logo_light_url||img.src)}}
 function readyOnce(){let tries=0;const timer=setInterval(()=>{tries++;if(arrange()){clearInterval(timer);bind();render();syncLogo()}else if(tries>60)clearInterval(timer)},100)}
 function init(){readyOnce();document.addEventListener('click',e=>{if(e.target.closest?.('.sp-nav-btn[data-sp-view="home"]'))setTimeout(()=>{arrange();bind();render();syncLogo()},30)},true)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();