(()=>{
 const getJobs=()=>{try{if(Array.isArray(window.jobs))return window.jobs;if(typeof jobs!=='undefined'&&Array.isArray(jobs))return jobs}catch(_){}return[]};
 const norm=s=>String(s||'').trim().toLowerCase().replace(/[\s_-]+/g,'');
 const statusLabel=j=>{try{if(typeof statusText==='function')return statusText(j)}catch(_){}return String(j?.status||'')};
 const category=(j,key)=>{const s=norm(j.status),label=norm(statusLabel(j));if(key==='all')return true;if(key==='scheduled')return !!j.scheduled_date&&s!=='completed'&&s!=='waiting'&&!label.includes('followup');if(key==='progress')return s==='inprogress'||label==='inprogress';if(key==='followup')return s==='waiting'||s==='followup'||label.includes('followup');if(key==='completed')return s==='completed'||label==='completed';if(key==='overdue'){const today=typeof localDate==='function'?localDate():new Date().toISOString().slice(0,10);return !!j.scheduled_date&&j.scheduled_date<today&&s!=='completed'}return true};
 function renderHomeFilter(key){const root=document.getElementById('spUpcoming');if(!root)return;const list=getJobs().filter(j=>category(j,key)).sort((a,b)=>(a.scheduled_date||'9999').localeCompare(b.scheduled_date||'9999')||(a.scheduled_start||'99:99').localeCompare(b.scheduled_start||'99:99'));const card=window.homeCard||(typeof homeCard==='function'?homeCard:null);if(card){root.innerHTML=list.length?list.map(card).join(''):'<div class="sp-home-empty">No jobs in this category.</div>';const binder=window.bindHomeCards||(typeof bindHomeCards==='function'?bindHomeCards:null);if(binder)binder()}}
 function bindStats(){const stats=document.getElementById('spStats');if(!stats||stats.dataset.v076)return;stats.dataset.v076='1';const keys=['all','scheduled','progress','followup','completed','overdue'];[...stats.querySelectorAll('.sp-stat-tile')].forEach((t,i)=>t.dataset.v076key=keys[i]||'all');const run=e=>{const t=e.target.closest('.sp-stat-tile');if(!t)return;e.preventDefault();e.stopPropagation();stats.querySelectorAll('.sp-stat-tile').forEach(x=>x.classList.toggle('selected',x===t));renderHomeFilter(t.dataset.v076key)};stats.addEventListener('pointerup',run,true);stats.addEventListener('click',e=>{if(e.detail===0)run(e)},true)}
 function pin(){const btn=document.getElementById('viewOnMapBtn');if(!btn||btn.dataset.pinReady==='1')return;btn.dataset.pinReady='1';btn.innerHTML='<svg class="sp-real-pin" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 22C9.8 19.1 5 14.7 5 9.5a7 7 0 1 1 14 0C19 14.7 14.2 19.1 12 22Z"/><circle cx="12" cy="9.5" r="2.5"/></svg><span>View</span>'}
 function boot(){bindStats();pin();const mo=new MutationObserver(()=>{bindStats();pin()});mo.observe(document.body,{childList:true,subtree:true})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();